name: 🚀 Publish to Velog

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use velog-actions
        uses: sabeurthabti/velog-actions@v1.1.0
        with:
          token: ${{ secrets.GH_PAT2 }}
          directory: posts